# Generated by Django 4.1.6 on 2023-02-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ForeignNationalInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FirstName", models.CharField(max_length=500)),
                ("MiddleName", models.CharField(blank=True, max_length=500)),
                ("LastName", models.CharField(max_length=500)),
                ("Date_of_Birth", models.DateField()),
                ("Email", models.EmailField(max_length=254)),
                ("Phone", models.CharField(max_length=10)),
                ("SSN", models.CharField(max_length=500)),
            ],
        )
    ]
