# Generated by Django 4.1.6 on 2023-02-09 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("api", "0002_address_foreignnationalinfo_presentaddress_and_more")]

    operations = [
        migrations.AddField(
            model_name="foreignnationalinfo",
            name="copyprevtopresentAddr",
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name="foreignnationalinfo",
            name="mailingAddress",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mailingAddress",
                to="api.address",
            ),
        ),
        migrations.AlterField(
            model_name="foreignnationalinfo",
            name="presentAddress",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="presentAddress",
                to="api.address",
            ),
        ),
    ]
