# Generated by Django 4.1.6 on 2023-02-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0003_foreignnationalinfo_copyprevtopresentaddr_and_more")]

    operations = [
        migrations.AlterField(
            model_name="foreignnationalinfo",
            name="previousAddresses",
            field=models.ManyToManyField(
                blank=True, related_name="previousAddress", to="api.address"
            ),
        )
    ]
